FROM eclipse-temurin:24

ARG HOST_DB_INFO
ARG CONTAINER_DB_INFO
ARG HOST_KAFKA_CONFIG
ARG CONTAINER_KAFKA_CONFIG
ARG HOST_EMAIL_INFO
ARG CONTAINER_EMAIL_INFO

COPY $HOST_DB_INFO $CONTAINER_DB_INFO
COPY $HOST_KAFKA_CONFIG $CONTAINER_KAFKA_CONFIG
COPY $HOST_KAFKA_CONFIG $CONTAINER_EMAIL_INFO
COPY resources/log.properties /etc/log.properties

ENV LOG_CONFIG=/etc/log.properties