FROM eclipse-temurin:24

ARG HOST_DB_INFO
ARG CONTAINER_DB_INFO
ARG HOST_KAFKA_CONFIG
ARG CONTAINER_KAFKA_CONFIG
ARG HOST_EMAIL_INFO
ARG CONTAINER_EMAIL_INFO
ARG HOST_AIRPORTS
ARG CONTAINER_AIRPORTS
ARG HOST_RUNWAYS
ARG CONTAINER_RUNWAYS

COPY $HOST_DB_INFO $CONTAINER_DB_INFO
COPY $HOST_KAFKA_CONFIG $CONTAINER_KAFKA_CONFIG
COPY $HOST_EMAIL_INFO $CONTAINER_EMAIL_INFO
COPY resources/log.properties /etc/log.properties
COPY $HOST_AIRPORTS $CONTAINER_AIRPORTS
COPY $HOST_RUNWAYS $CONTAINER_RUNWAYS

ENV LOG_CONFIG=/etc/log.properties