--liquibase formatted sql

--changeset pujan:event-definitions-static labels:messages

INSERT INTO event_definitions (fleet_id, airframe_id, airframe_type_id, name, start_buffer, stop_buffer, column_names, condition_json, severity_column_names, severity_type, color)
VALUES
    (0, 0, 2, 'CLIMB_RATE_BELOW_10KTS::LOW', 5, 1, '["GndSpd","VSpd"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["GndSpd","<","10"]},{"type":"RULE","inputs":["VSpd",">=","1500"]}]}',
     '["VSpd"]', 'MAX', NULL),
    (0, 0, 2, 'CLIMB_RATE_BELOW_10KTS::MEDIUM', 5, 1, '["GndSpd","VSpd"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["GndSpd","<","10"]},{"type":"RULE","inputs":["VSpd",">=","1750"]}]}',
     '["VSpd"]', 'MAX', NULL),
    (0, 0, 2, 'CLIMB_RATE_BELOW_10KTS::HIGH', 5, 1, '["GndSpd","VSpd"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["GndSpd","<","10"]},{"type":"RULE","inputs":["VSpd",">=","2000"]}]}',
     '["VSpd"]', 'MAX', NULL),
    (0, 0, 2, 'DESCENT_RATE_ABOVE_300FT::LOW', 4, 1, '["AltAGL","VSpd"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["AltAGL",">","300"]},{"type":"RULE","inputs":["VSpd","<=","-1250"]}]}',
     '["VSpd"]', 'MIN', NULL),
    (0, 0, 2, 'DESCENT_RATE_ABOVE_300FT::MEDIUM', 4, 1, '["AltAGL","VSpd"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["AltAGL",">","300"]},{"type":"RULE","inputs":["VSpd","<=","-1500"]}]}',
     '["VSpd"]', 'MIN', NULL),
    (0, 0, 2, 'DESCENT_RATE_ABOVE_300FT::HIGH', 4, 1, '["AltAGL","VSpd"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["AltAGL",">","300"]},{"type":"RULE","inputs":["VSpd","<=","-2000"]}]}',
     '["VSpd"]', 'MIN', NULL),
    (0, 0, 2, 'GROUNDSPEED_BELOW_100FT::LOW', 5, 1, '["AltAGL","GndSpd"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["AltAGL","<","100"]},{"type":"RULE","inputs":["GndSpd",">=","90"]}]}',
     '["GndSpd"]', 'MAX', NULL),
    (0, 0, 2, 'GROUNDSPEED_BELOW_100FT::MEDIUM', 5, 1, '["AltAGL","GndSpd"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["AltAGL","<","100"]},{"type":"RULE","inputs":["GndSpd",">=","100"]}]}',
     '["GndSpd"]', 'MAX', NULL),
    (0, 0, 2, 'GROUNDSPEED_BELOW_100FT::HIGH', 5, 1, '["AltAGL","GndSpd"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["AltAGL","<","100"]},{"type":"RULE","inputs":["GndSpd",">=","110"]}]}',
     '["GndSpd"]', 'MAX', NULL),
    (0, 0, 2, 'PITCH_EXCESSIVE::HIGH', 3, 1, '["Pitch"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["Pitch",">","30"]}]}',
     '["Pitch"]', 'MAX', NULL),
    (0, 0, 2, 'ROLL_ABOVE_300FT::LOW', 4, 1, '["AltAGL","Roll"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["AltAGL",">=","300"]},{"type":"RULE","inputs":["Roll",">=","40"]}]}',
     '["Roll"]', 'MAX', NULL),
    (0, 0, 2, 'ROLL_ABOVE_300FT::MEDIUM', 4, 1, '["AltAGL","Roll"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["AltAGL",">=","300"]},{"type":"RULE","inputs":["Roll",">=","50"]}]}',
     '["Roll"]', 'MAX', NULL),
    (0, 0, 2, 'ROLL_ABOVE_300FT::HIGH', 4, 1, '["AltAGL","Roll"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["AltAGL",">=","300"]},{"type":"RULE","inputs":["Roll",">=","55"]}]}',
     '["Roll"]', 'MAX', NULL),
    (0, 0, 2, 'ROLL_EXCESSIVE::HIGH', 1, 1, '["Roll"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["Roll",">=","60"]}]}',
     '["Roll"]', 'MAX', NULL),
    (0, 0, 2, 'YAW_RATE::LOW', 3, 1, '["Yaw Rate"]',
     '{"type":"GROUP","condition":"OR","filters":[{"type":"RULE","inputs":["Yaw Rate",">=","5"]},{"type":"RULE","inputs":["Yaw Rate","<=","-5"]}]}',
     '["Yaw Rate"]', 'MAX_ABS', NULL),
    (0, 0, 2, 'YAW_RATE::MEDIUM', 3, 1, '["Yaw Rate"]',
     '{"type":"GROUP","condition":"OR","filters":[{"type":"RULE","inputs":["Yaw Rate",">=","10"]},{"type":"RULE","inputs":["Yaw Rate","<=","-10"]}]}',
     '["Yaw Rate"]', 'MAX_ABS', NULL),
    (0, 0, 2, 'YAW_RATE::HIGH', 3, 1, '["Yaw Rate"]',
     '{"type":"GROUP","condition":"OR","filters":[{"type":"RULE","inputs":["Yaw Rate",">=","15"]},{"type":"RULE","inputs":["Yaw Rate","<=","-15"]}]}',
     '["Yaw Rate"]', 'MAX_ABS', NULL);

