--liquibase formatted sql

--changeset pujan:event-definitions-static labels:messages

INSERT INTO event_definitions (id, fleet_id, airframe_id, airframe_type_id, name, start_buffer, stop_buffer, column_names, condition_json, severity_column_names, severity_type, color)
VALUES
    (73, 0, 0, 2, 'Low Climb Rate Below 10kts', 5, 1, '["GndSpd","VSpd"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["GndSpd","<","10"]},{"type":"RULE","inputs":["VSpd",">=","1500"]},{"type":"RULE","inputs":["VSpd","<","1750"]}]}',
     '["VSpd"]', 'MAX', NULL),
    (74,0, 0, 2, 'Medium Climb Rate Below 10kts', 5, 1, '["GndSpd","VSpd"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["GndSpd","<","10"]},{"type":"RULE","inputs":["VSpd",">=","1750"]},{"type":"RULE","inputs":["VSpd","<","2000"]}]}',
     '["VSpd"]', 'MAX', NULL),
    (75,0, 0, 2, 'High Climb Rate Below 10kts', 5, 1, '["GndSpd","VSpd"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["GndSpd","<","10"]},{"type":"RULE","inputs":["VSpd",">=","2000"]}]}',
     '["VSpd"]', 'MAX', NULL),
    (76,0, 0, 2, 'Low Descent Rate Above 300ft', 4, 1, '["AltAGL","VSpd"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["AltAGL",">","300"]},{"type":"RULE","inputs":["VSpd","<=","-1250"]},{"type":"RULE","inputs":["VSpd",">","-1500"]}]}',
     '["VSpd"]', 'MIN', NULL),
    (77,0, 0, 2, 'Medium Descent Rate Above 300ft', 4, 1, '["AltAGL","VSpd"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["AltAGL",">","300"]},{"type":"RULE","inputs":["VSpd","<=","-1500"]},{"type":"RULE","inputs":["VSpd",">","-2000"]}]}',
     '["VSpd"]', 'MIN', NULL),
    (78,0, 0, 2, 'High Descent Rate Above 300ft', 4, 1, '["AltAGL","VSpd"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["AltAGL",">","300"]},{"type":"RULE","inputs":["VSpd","<=","-2000"]}]}',
     '["VSpd"]', 'MIN', NULL),
    (79,0, 0, 2, 'Low Groundspeed Below 100ft', 5, 1, '["AltAGL","GndSpd"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["AltAGL","<","100"]},{"type":"RULE","inputs":["GndSpd",">=","90"]},{"type":"RULE","inputs":["GndSpd","<","100"]}]}',
     '["GndSpd"]', 'MAX', NULL),
    (80,0, 0, 2, 'Medium Groundspeed Below 100ft', 5, 1, '["AltAGL","GndSpd"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["AltAGL","<","100"]},{"type":"RULE","inputs":["GndSpd",">=","100"]},{"type":"RULE","inputs":["GndSpd","<","110"]}]}',
     '["GndSpd"]', 'MAX', NULL),
    (81,0, 0, 2, 'High Groundspeed Below 100ft', 5, 1, '["AltAGL","GndSpd"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["AltAGL","<","100"]},{"type":"RULE","inputs":["GndSpd",">=","110"]}]}',
     '["GndSpd"]', 'MAX', NULL),
    (82,0, 0, 2, 'High Pitch Excessive', 3, 1, '["Pitch"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["Pitch",">","30"]}]}',
     '["Pitch"]', 'MAX', NULL),
    (83,0, 0, 2, 'Low Roll Above 300ft', 4, 1, '["AltAGL","Roll"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["AltAGL",">=","300"]},{"type":"RULE","inputs":["Roll",">=","40"]},{"type":"RULE","inputs":["Roll","<","50"]}]}',
     '["Roll"]', 'MAX', NULL),
    (84,0, 0, 2, 'Medium Roll Above 300ft', 4, 1, '["AltAGL","Roll"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["AltAGL",">=","300"]},{"type":"RULE","inputs":["Roll",">=","50"]},{"type":"RULE","inputs":["Roll","<","55"]}]}',
     '["Roll"]', 'MAX', NULL),
    (85,0, 0, 2, 'High Roll Above 300ft', 4, 1, '["AltAGL","Roll"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["AltAGL",">=","300"]},{"type":"RULE","inputs":["Roll",">=","55"]}]}',
     '["Roll"]', 'MAX', NULL),
    (86,0, 0, 2, 'High Roll Excessive', 1, 1, '["Roll"]',
     '{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["Roll",">=","60"]}]}',
     '["Roll"]', 'MAX', NULL),
    (87,0, 0, 2, 'Low Yaw Rate', 3, 1, '["Yaw Rate"]',
     '{"type":"GROUP","condition":"OR","filters":[{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["Yaw Rate",">=","5"]},{"type":"RULE","inputs":["Yaw Rate","<","10"]}]},{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["Yaw Rate","<=","-5"]},{"type":"RULE","inputs":["Yaw Rate",">","-10"]}]}]}',
     '["Yaw Rate"]', 'MAX_ABS', NULL),
    (88,0, 0, 2, 'Medium Yaw Rate', 3, 1, '["Yaw Rate"]',
     '{"type":"GROUP","condition":"OR","filters":[{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["Yaw Rate",">=","10"]},{"type":"RULE","inputs":["Yaw Rate","<","15"]}]},{"type":"GROUP","condition":"AND","filters":[{"type":"RULE","inputs":["Yaw Rate","<=","-10"]},{"type":"RULE","inputs":["Yaw Rate",">","-15"]}]}]}',
     '["Yaw Rate"]', 'MAX_ABS', NULL),
    (89,0, 0, 2, 'High Yaw Rate', 3, 1, '["Yaw Rate"]',
     '{"type":"GROUP","condition":"OR","filters":[{"type":"RULE","inputs":["Yaw Rate",">=","15"]},{"type":"RULE","inputs":["Yaw Rate","<=","-15"]}]}',
     '["Yaw Rate"]', 'MAX_ABS', NULL);

