#!/bin/bash
# We add skip assembly to skip generating jars w/ their dependencies which takes some time. use the `package` script.

do_clean=false
skip_tests=true

while [[ $# -gt 0 ]]; do
	case "$1" in
		--clean)
			do_clean=true
			shift
			;;
		--skip-tests)
			skip_tests=true
			shift
			;;
		--no-skip-tests)
			skip_tests=false
			shift
			;;
		*)
			shift
			;;
	esac
done

goals=(install)
if $do_clean; then
	goals=(clean install)
fi

extra_args=()
if $skip_tests; then
	extra_args+=("-Dmaven.test.skip=true")
fi

mvn "${goals[@]}" -pl '!ngafid-db' -Dassembly.skipAssembly=true "${extra_args[@]}"
