#!/bin/bash

# Change to the project root directory
cd "$(dirname "$0")/../.."

# Use the shaded JAR with dependencies directly
java -XX:MaxRAMPercentage=95.0 -cp ngafid-data-processor/target/ngafid-data-processor-1.0-SNAPSHOT-jar-with-dependencies.jar org.ngafid.processor.UploadConsumer

