#!/bin/bash

# Change to the project root directory
cd "$(dirname "$0")/../.."


# TODO: Actually fix the CPU usage problem of the UploadConsumer
# instead of just lobotomizing it here.


export MAX_CACHE_SIZE=75

# Check OS and use appropriate command
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Use the shaded JAR with dependencies directly
    exec taskset -c 0-3 java $JAVA_OPTS -cp ngafid-data-processor/target/ngafid-data-processor-1.0-SNAPSHOT-jar-with-dependencies.jar org.ngafid.processor.UploadConsumer
else
    # Use the shaded JAR with dependencies directly
    exec java $JAVA_OPTS -cp ngafid-data-processor/target/ngafid-data-processor-1.0-SNAPSHOT-jar-with-dependencies.jar org.ngafid.processor.UploadConsumer
fi

