name: Publish JavaDoc to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.java'
      - '**/*.kt'
      - '**/pom.xml'
      - '.github/workflows/javadoc-publish.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Setup DAT2CSV
        run: run/setup_dat_importing
        
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
            
      - name: Generate JavaDoc
        run: |
          mvn clean javadoc:javadoc -DskipTests
          # Create a combined JavaDoc site
          mkdir -p target/site/javadoc
          echo "<html><head><title>NGAFID 2.0 JavaDoc</title></head><body>" > target/site/javadoc/index.html
          echo "<h1>NGAFID 2.0 JavaDoc</h1>" >> target/site/javadoc/index.html
          echo "<ul>" >> target/site/javadoc/index.html
          echo "<li><a href='ngafid-core/'>ngafid-core</a></li>" >> target/site/javadoc/index.html
          echo "<li><a href='ngafid-www/'>ngafid-www</a></li>" >> target/site/javadoc/index.html
          echo "<li><a href='ngafid-data-processor/'>ngafid-data-processor</a></li>" >> target/site/javadoc/index.html
          echo "<li><a href='ngafid-db/'>ngafid-db</a></li>" >> target/site/javadoc/index.html
          echo "<li><a href='ngafid-airsync/'>ngafid-airsync</a></li>" >> target/site/javadoc/index.html
          echo "</ul></body></html>" >> target/site/javadoc/index.html
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/site/javadoc
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
