name: Compile NGAFID

on:
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup JDK 11
              uses: actions/setup-java@v3
              with:
                java-version: 11
                distribution: 'oracle'

            - name: Maven Build
              run: mvn clean compile -DskipTests

            - name: Maven Test
              run: mvn test
